import { Level, Operator, Gender } from '@prisma/client'

export const gobletSquatsFemale60To69 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 90, reps: 3,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 46,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 75,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 100, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 72,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 110, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 42,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 69,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 120, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 66,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 130, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 40,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 63,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 140, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 61,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 150, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 19,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 37,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 58,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 160, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 19,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 36,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 56,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 170, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 54,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 180, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 53,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 190, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 51,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 200, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 49,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 210, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 220, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 47,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 230, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 45,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 240, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 43,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 250, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 260, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 41,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
