import { Level, Operator, Gender } from '@prisma/client'

export const gobletSquatsFemale70To79 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 90, reps: 2,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 36,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 60,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 100, reps: 3,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 57,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 110, reps: 3,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 55,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 120, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 52,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 130, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 50,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 140, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 150, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 30,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 47,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 160, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 45,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 170, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 43,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 180, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 190, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 200, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 39,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 210, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 25,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 38,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 220, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 24,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 230, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 24,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 240, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 35,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 250, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 34,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 260, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 33,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
