import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const gobletSquatsFemale40To49 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 63,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 103,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 61,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 99,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 58,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 95,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 57,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 90,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 55,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 87,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 83,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 81,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 78,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 75,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 73,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 70,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 68,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 66,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 57,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
