import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const gobletSquatsFemale24To39 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 66,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 109,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 64,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 104,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 62,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 100,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 60,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 95,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 58,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 92,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 56,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 88,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 54,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 85,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 82,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 82,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 74,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 71,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 8,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 45,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 68,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 65,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
