import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const gobletSquatsFemale18To23 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 65,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 107,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 62,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 102,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 60,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 98,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 59,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 93,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 57,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 90,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 55,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 86,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 83,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 80,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 72,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 70,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 68,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 66,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 59,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
