import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const gobletSquatsFemale60To69 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 75,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 72,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 66,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 61,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 36,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 54,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 53,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 33,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 51,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 32,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 49,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 47,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 45,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 43,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 41,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
