import { Level, Operator, Gender } from '@prisma/client'

export const gobletSquatsFemale40To49 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 90, reps: 4,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 63,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 103,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 100, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 61,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 99,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 110, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 58,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 95,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 120, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 57,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 90,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 130, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 55,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 87,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 140, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 53,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 83,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 150, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 51,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 81,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 160, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 50,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 78,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 170, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 25,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 48,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 75,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 180, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 25,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 47,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 73,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 190, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 24,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 46,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 70,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 200, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 24,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 68,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 210, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 43,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 66,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 220, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 42,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 64,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 230, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 62,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 240, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 60,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 250, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 38,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 58,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 260, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 38,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 57,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
