import { Level, Operator, Gender } from '@prisma/client'

export const gobletSquatsFemale24To39 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 90, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 66,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 90, reps: 109,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 100, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 64,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 100, reps: 104,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 110, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 62,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 110, reps: 100,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 120, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 60,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 120, reps: 95,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 130, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 58,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 130, reps: 92,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 140, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 56,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 140, reps: 88,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 150, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 54,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 150, reps: 85,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 160, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 53,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 160, reps: 82,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 170, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 53,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 170, reps: 82,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 180, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 50,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 180, reps: 77,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 190, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 48,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 190, reps: 74,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 200, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 25,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 47,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 200, reps: 71,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 210, reps: 8,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 24,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 45,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 210, reps: 69,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 220, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 220, reps: 68,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 230, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 43,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 230, reps: 65,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 240, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 240, reps: 63,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 250, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 250, reps: 62,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats', operator: Operator.LESS_THAN },
  { weight: 260, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 40,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: 260, reps: 60,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
