import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const gobletSquatsFemale14To17 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 57,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.NINETY, reps: 95,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 55,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED, reps: 91,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 9,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 54,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 87,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 52,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 83,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 80,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 49,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 76,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 74,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 71,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 59,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 57,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 36,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 55,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 54,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 52,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'gobletSquats' },
]
