import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const pushupsFemale40To49 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.NINETY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.NINETY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.NINETY, reps: 59,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED, reps: 36,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED, reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 53,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 51,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 32,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 49,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 30,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 46,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 44,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 40,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 26,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 38,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 24,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 36,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 34,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 22,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 33,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'pushUp' },
]
