import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const pushupsMale40To49 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 39,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 70,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 105,  level: Level.ELITE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 39,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 69,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 103,  level: Level.ELITE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 39,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 67,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 100,  level: Level.ELITE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 39,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 67,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 97,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 39,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 65,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 94,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 38,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 64,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 92,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 38,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 63,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 89,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 37,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 61,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 87,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 37,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 60,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 85,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 58,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 83,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 35,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 57,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 81,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 35,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 56,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 79,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 17,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 54,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 33,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 75,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 33,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 52,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 73,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 71,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 31,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 31,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 68,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 66,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 4,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
