import { Level, Operator, Gender } from '@prisma/client'

export const pushupsMale70To79 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 110, reps: 8,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 61,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 120, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 40,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 59,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 130, reps: 9,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 58,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 140, reps: 9,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 56,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 150, reps: 9,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 37,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 54,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 37,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 53,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 36,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 52,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 180, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 51,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 190, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 49,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 200, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 210, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 47,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 220, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 46,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 230, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 45,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 240, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 19,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 43,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 250, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 19,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 30,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 260, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 270, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 280, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 290, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 39,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 300, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 9,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 38,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 310, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 8,  level: Level.INTERMEDIATE,  age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
