import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const pushupsMale40To49 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 61,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 92,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 61,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 90,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 59,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 87,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 58,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 85,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 56,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 82,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 33,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 56,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 81,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 33,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 55,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 78,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 76,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 52,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 74,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 72,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 31,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 71,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 31,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 49,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 66,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 45,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 61,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 57,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
