import { Level, Operator, Gender } from '@prisma/client'

export const pushupsMale14To17 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 110, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 64,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 97,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 120, reps: 13,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 64,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 94,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 130, reps: 14,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 62,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 91,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 140, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 61,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 89,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 150, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 59,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 86,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 35,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 58,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 84,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 170, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 35,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 57,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 82,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 180, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 34,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 56,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 80,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 190, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 34,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 55,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 77,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 200, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 33,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 53,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 76,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 210, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 32,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 52,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 74,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 220, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 32,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 51,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 72,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 230, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 31,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 50,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 70,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 240, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 49,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 69,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 250, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 48,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 67,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 260, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 30,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 47,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 65,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 270, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 46,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 64,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 280, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 14,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 29,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 63,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 290, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 14,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 61,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 300, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 14,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 43,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 60,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 310, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 13,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 43,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 58,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
