import { Level, Operator, Gender } from '@prisma/client'

export const pushupsMale60To69 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 110, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 51,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 77,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 120, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 50,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 75,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 130, reps: 11,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 49,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 72,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 140, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 48,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 70,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 150, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 47,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 68,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 46,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 67,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 28,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 46,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 65,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 180, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 44,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 63,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 27,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 43,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 61,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 200, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 42,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 60,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 210, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 59,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 220, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 26,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 57,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 230, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 25,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 56,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 240, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 24,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 55,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 250, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 24,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 38,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 53,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 260, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 37,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 52,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 270, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 12,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 37,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 50,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 280, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 11,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 23,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 50,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 290, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 11,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 300, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 11,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 310, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 10,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 46,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
