import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const pushupsMale14To17 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 64,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 97,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 64,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 94,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 62,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 91,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 61,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 89,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 36,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 59,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 86,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 35,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 58,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 84,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 35,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 57,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 82,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 56,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 80,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 34,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 55,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 33,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 53,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 76,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 52,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 74,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 32,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 72,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 16,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 31,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 70,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 49,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 69,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 30,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 65,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 15,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 29,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 61,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 14,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 13,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
