import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const pushupsMale60To69 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 10,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 51,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 77,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 10,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 50,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 75,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 11,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 49,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 72,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 48,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 70,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 47,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 68,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 28,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 46,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 65,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 44,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 27,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 61,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 59,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 26,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 57,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 25,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 55,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 24,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 53,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 52,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 12,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 50,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 11,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 23,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 50,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 11,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 11,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 3,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 10,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 33,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 46,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
