import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const invertedRowFemale14To17 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.NINETY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.NINETY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.NINETY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.NINETY, reps: 33,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED, reps: 2,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 31,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 28,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 28,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 10,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 27,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 25,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 24,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 9,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 16,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 9,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 16,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 9,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 22,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 9,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 21,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'invertedRow' },
]
