import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const invertedRowMale60To69 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 2,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 36,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 36,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 35,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 35,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 34,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 33,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 22,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 22,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 31,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 28,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 12,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 27,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 19,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 11,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.THREE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 25,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 25,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
]
