import { Level, Operator, Gender } from '@prisma/client'

export const invertedRowMale24To39 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 110, reps: 2,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 53,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 120, reps: 3,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 52,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 130, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 52,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 140, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 51,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 150, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 50,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 160, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 49,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 170, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 48,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 180, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 47,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 190, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 46,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 200, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 45,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 210, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 45,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 220, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 30,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 43,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 230, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 30,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 240, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 250, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 41,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 260, reps: 8,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 270, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 270, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 39,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 280, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 280, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 38,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 290, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 290, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 300, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 300, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 310, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 310, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 25,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
]
