import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const invertedRowMale80To89 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 2,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 2,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 22,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 22,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 22,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 21,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 21,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 20,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED, reps: 20,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 19,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 8,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 19,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 12,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 12,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 12,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 17,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 12,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 17,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 11,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 16,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.THREE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 11,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED, reps: 16,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 7,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 11,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 16,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'invertedRow' },
]
