import { Level, Operator, Gender } from '@prisma/client'

export const invertedRowMale60To69 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 110, reps: 1,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 11,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 110, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 120, reps: 2,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 120, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 130, reps: 3,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 130, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 140, reps: 3,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 140, reps: 35,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 150, reps: 4,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 150, reps: 35,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 160, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 160, reps: 34,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 170, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 170, reps: 33,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 180, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 180, reps: 32,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 190, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 190, reps: 32,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 200, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 200, reps: 31,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 210, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 210, reps: 30,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 220, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 220, reps: 30,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 230, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 230, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 240, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 20,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 240, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 250, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 250, reps: 28,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 260, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 260, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 270, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 270, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 11,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 270, reps: 27,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 280, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 280, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 11,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 280, reps: 26,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 290, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 290, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 11,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 18,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 290, reps: 26,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 300, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 300, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 10,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 18,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 300, reps: 25,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },

  { weight: 310, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'invertedRow', operator: Operator.LESS_THAN },
  { weight: 310, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 10,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 17,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
  { weight: 310, reps: 25,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'invertedRow' },
]
