import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const backExtensionsFemale18To23 = [
  { weight: WeightRange.NINETY, startReps: 1, endReps: 4,      level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 5, endReps: 21,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 22, endReps: 41,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 42, endReps: 65,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 66, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 6, endReps: 21,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 22, endReps: 40,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 41, endReps: 63,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 63, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 7, endReps: 21,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 22, endReps: 39,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 40, endReps: 61,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 62, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 7, endReps: 20,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 21, endReps: 38,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 39, endReps: 58,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 59, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 7, endReps: 20,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 21, endReps: 37,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 38, endReps: 56,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 57, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 7, endReps: 20,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 21, endReps: 35,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 36, endReps: 54,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 55, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 7, endReps: 19,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 20, endReps: 34,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 35, endReps: 52,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 53, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 7, endReps: 19,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 20, endReps: 33,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 34, endReps: 50,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 51, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 7, endReps: 18,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 19, endReps: 32,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 33, endReps: 48,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 49, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 7, endReps: 17,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 18, endReps: 31,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 32, endReps: 46,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 47, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 7, endReps: 17,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 18, endReps: 30,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 31, endReps: 45,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 46, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, startReps: 1, endReps: 6,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 7, endReps: 16,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 17, endReps: 29,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 30, endReps: 43,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 44, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 6, endReps: 16,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 17, endReps: 28,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 29, endReps: 41,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 42, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 6, endReps: 15,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 16, endReps: 27,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 28, endReps: 40,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 41, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 6, endReps: 14,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 15, endReps: 26,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 27, endReps: 39,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 40, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 6, endReps: 15,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 16, endReps: 25,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 26, endReps: 37,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 38, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 1, endReps: 4,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 5, endReps: 13,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 14, endReps: 24,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 25, endReps: 36,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 37, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 1, endReps: 4,     level: Level.NOVICE,       ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 5, endReps: 13,   level: Level.INTERMEDIATE, ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 14, endReps: 24,    level: Level.PROFICIENT,   ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 25, endReps: 35,    level: Level.ADVANCED,     ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 36, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.EIGHTEEN_TO_TWENTY_THREE, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
