import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const backExtensionsFemale14To17 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 4,  level: Level.INTERMEDIATE,  ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 19,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 37,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 58,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 5,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 19,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 37,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 57,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 19,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 36,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 55,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 18,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 35,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 52,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 18,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 34,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 50,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 18,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 32,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 49,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 17,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 31,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 47,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 17,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 30,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 45,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 17,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 30,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 44,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 16,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 29,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 42,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 16,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 28,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 41,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 6,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 15,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 27,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 39,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 5,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 15,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 26,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 37,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 14,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 25,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 37,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 13,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 24,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 36,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 13,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 23,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 34,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 12,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 23,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 33,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 4,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 12,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 22,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 32,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
