import { Level, Operator, Gender } from '@prisma/client'

export const backExtensionsFemale18To23 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 90, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 90, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 90, reps: 42,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 90, reps: 66,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 100, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 100, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 100, reps: 41,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 100, reps: 64,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 110, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 110, reps: 22,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 110, reps: 40,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 110, reps: 62,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 120, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 120, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 120, reps: 39,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 120, reps: 59,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 130, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 130, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 130, reps: 38,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 130, reps: 57,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 140, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 140, reps: 21,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 140, reps: 36,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 140, reps: 55,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 150, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 150, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 150, reps: 35,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 150, reps: 53,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 160, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 160, reps: 20,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 160, reps: 34,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 160, reps: 51,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 170, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 170, reps: 19,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 170, reps: 33,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 170, reps: 49,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 180, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 180, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 180, reps: 32,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 180, reps: 47,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 190, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 190, reps: 18,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 190, reps: 31,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 190, reps: 46,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 200, reps: 7,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 200, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 200, reps: 30,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 200, reps: 44,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 210, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 210, reps: 17,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 210, reps: 29,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 210, reps: 42,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 220, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 220, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 220, reps: 28,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 220, reps: 41,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 230, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 230, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 230, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 230, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 240, reps: 6,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 240, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 240, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 240, reps: 38,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 250, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 250, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 250, reps: 25,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 250, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'backExtensions', operator: Operator.LESS_THAN },
  { weight: 260, reps: 5,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 260, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 260, reps: 25,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
  { weight: 260, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'backExtensions' },
]
