import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const backExtensionsFemale14To17 = [
  { weight: WeightRange.NINETY, startReps: 1,  endReps: 3,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 4,  endReps: 18,    level: Level.INTERMEDIATE,  ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 19, endReps: 36,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 37, endReps: 57,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 58, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, startReps: 1, endReps: 4,      level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 5, endReps: 18,     level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 19, endReps: 36,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 37, endReps: 56,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 57, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 1, endReps: 5,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 6, endReps: 18,    level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 19, endReps: 35,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 36, endReps: 54,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 55, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 1, endReps: 5,  level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 6, endReps: 17, level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 18, endReps: 34,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 35, endReps: 51,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 52, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 1, endReps: 5,  level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 6, endReps: 17, level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 18, endReps: 33,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 34, endReps: 49,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 50, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 1, endReps: 5,   level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 6, endReps: 17, level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 18, endReps: 31,  level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 32, endReps: 48,  level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 49, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 1, endReps: 5,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 6, endReps: 16,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 17, endReps: 30,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 31, endReps: 46,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 47, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 1, endReps: 5,        level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 6, endReps: 16,      level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 17, endReps: 29,       level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 30, endReps: 44,       level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: 45, endReps: 1000,       level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 1, endReps: 5,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 6, endReps: 16,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 17, endReps: 29,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 30, endReps: 43,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: 44, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 1, endReps: 5,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 6, endReps: 15,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 16, endReps: 28,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 29, endReps: 41,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: 42, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 1, endReps: 5,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 6, endReps: 15,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 16, endReps: 27,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 28, endReps: 40,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: 41, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, startReps: 1, endReps: 5,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 6, endReps: 14,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 15, endReps: 26,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 27, endReps: 38,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: 39, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 1, endReps: 4,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 5, endReps: 14,   level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 15, endReps: 25,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 26, endReps: 36,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: 37, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 1, endReps: 4,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 5, endReps: 13,   level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 14, endReps: 24,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 25, endReps: 36,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: 37, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 1, endReps: 4,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 5, endReps: 12,   level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 13, endReps: 23,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 24, endReps: 35,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: 36, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 1, endReps: 4,    level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 5, endReps: 12,  level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 13, endReps: 22,   level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 23, endReps: 33,   level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: 34, endReps: 1000,  level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 1, endReps: 3,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 4, endReps: 11,   level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 12, endReps: 22,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 23, endReps: 32,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: 33, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 1, endReps: 3,     level: Level.NOVICE,       ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 4, endReps: 11,   level: Level.INTERMEDIATE, ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 12, endReps: 21,    level: Level.PROFICIENT,   ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 22, endReps: 31,    level: Level.ADVANCED,     ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: 32, endReps: 1000,   level: Level.ELITE,        ageRange: AgeRange.FOURTEEN_TO_SEVENTEEN, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
