import { Level, Gender, AgeRange, WeightRange, ExerciseName }  from '@prisma/client'

export const backExtensionsFemale24To39 = [
  { weight: WeightRange.NINETY, startReps: 1, endReps: 4,   reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 5, endReps: 21,  reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 22, endReps: 42,  reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 43, endReps: 66,  reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, startReps: 67, endReps: 1000,  reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, startReps: 1, endReps: 5,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 6, endReps: 21,  reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 22, endReps: 41,  reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 42, endReps: 64,  reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, startReps: 65, endReps: 1000,  reps: 65,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 1, endReps: 6,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 7, endReps: 21,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 22, endReps: 40,  reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 41, endReps: 62,  reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, startReps: 63, endReps: 1000,  reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 1, endReps: 6,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 7, endReps: 20,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 21, endReps: 39,  reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 40, endReps: 59,  reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, startReps: 60, endReps: 1000,  reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 1, endReps: 6,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 7, endReps: 20,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 21, endReps: 38,  reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 39, endReps: 57,  reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, startReps: 58, endReps: 1000,  reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 1, endReps: 6,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 7, endReps: 20,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 21, endReps: 36,  reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 37, endReps: 55,  reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, startReps: 56, endReps: 1000,  reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 1, endReps: 6,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 7, endReps: 19,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: 20, endReps: 35,  reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 36,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 54,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 52,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: , endReps: ,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: , endReps: ,  reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: , endReps: ,  reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, startReps: , endReps: ,  reps: 50,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: , endReps: ,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: , endReps: ,  reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: , endReps: ,  reps: 33,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, startReps: , endReps: ,  reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: , endReps: ,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: , endReps: ,  reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: , endReps: ,  reps: 32,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, startReps: , endReps: ,  reps: 47,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: , endReps: ,  reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: , endReps: ,  reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: , endReps: ,  reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, startReps: , endReps: ,  reps: 45,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: , endReps: ,  reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: , endReps: ,  reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: , endReps: ,  reps: 30,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, startReps: , endReps: ,  reps: 43,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: , endReps: ,  reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: , endReps: ,  reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: , endReps: ,  reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, startReps: , endReps: ,  reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: , endReps: ,  reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: , endReps: ,  reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: , endReps: ,  reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, startReps: , endReps: ,  reps: 41,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: , endReps: ,  reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: , endReps: ,  reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: , endReps: ,  reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, startReps: , endReps: ,  reps: 39,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 26,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, startReps: , endReps: ,  reps: 38,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, startReps: , endReps: ,  reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
