import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const backExtensionsFemale40To49 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 64,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 62,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 38,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 57,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 55,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 53,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 51,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 33,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 49,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 32,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 46,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 30,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 45,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 43,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 41,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 40,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 39,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 26,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 36,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 24,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 35,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
