import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const backExtensionsFemale24To39 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 43,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.NINETY, reps: 67,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 42,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED, reps: 65,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 22,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 41,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 63,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 40,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 60,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 39,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 58,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 21,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 37,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 56,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 36,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 54,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 20,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 35,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 52,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 19,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 34,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 50,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 33,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 48,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 18,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 32,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 47,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 31,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED, reps: 45,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 30,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 43,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 41,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 39,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 26,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 38,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 5,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: ExerciseName.BACK_EXTENSION },
]
