import { Level, Operator, Gender } from '@prisma/client'

export const dipsFemale60To69 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 90, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 90, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 90, reps: 15,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 90, reps: 25,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 100, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 100, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 100, reps: 15,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 100, reps: 24,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 110, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 110, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 110, reps: 15,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 110, reps: 23,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 120, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 120, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 120, reps: 14,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 120, reps: 23,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 130, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 130, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 130, reps: 14,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 130, reps: 22,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 140, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 140, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 140, reps: 14,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 140, reps: 21,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 150, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 150, reps: 7,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 150, reps: 13,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 150, reps: 20,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 160, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 160, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 160, reps: 12,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 160, reps: 19,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 170, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 170, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 170, reps: 12,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 170, reps: 19,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 180, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 180, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 180, reps: 12,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 180, reps: 18,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 190, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 190, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 190, reps: 11,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 190, reps: 17,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 200, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 200, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 200, reps: 11,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 200, reps: 17,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 210, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 210, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 210, reps: 10,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 210, reps: 16,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 220, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 220, reps: 6,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 220, reps: 10,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 220, reps: 15,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 230, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 230, reps: 5,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 230, reps: 10,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 230, reps: 14,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 240, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 240, reps: 5,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 240, reps: 9,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 240, reps: 14,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 250, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 250, reps: 4,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 250, reps: 8,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 250, reps: 14,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 260, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 260, reps: 4,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 260, reps: 8,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'dips' },
  { weight: 260, reps: 13,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'dips' },
]
