import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const dipsMale14To17 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 43,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 6,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 42,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 29,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 41,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 40,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 39,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 38,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 27,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 26,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 37,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 17,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 36,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 25,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 35,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 24,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 34,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 16,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 24,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 33,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 32,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 15,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 31,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 23,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 8,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 22,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 14,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 22,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 30,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 2,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 21,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 29,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.THREE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 28,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 7,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 13,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 20,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 27,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
]
