import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const dipsMale70To79 = [
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 3,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 27,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 26,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 28,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 25,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 18,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 25,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 24,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 24,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 17,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 16,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED, reps: 23,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 16,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 22,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 21,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 10,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 21,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 9,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 15,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 20,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 9,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 20,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 9,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 19,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 5,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 9,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_SEVENTY, reps: 19,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 9,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 14,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_EIGHTY, reps: 19,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 8,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.TWO_HUNDRED_NINETY, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.THREE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 8,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED, reps: 18,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 4,   level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 8,   level: Level.PROFICIENT,   ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 13,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: WeightRange.THREE_HUNDRED_TEN, reps: 17,  level: Level.ELITE,        ageRange: 0, gender: Gender.MALE, exercise: 'dips' },
]
