import { Level, Operator, Gender } from '@prisma/client'

export const dipsMale50To59 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 110, reps: 5,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 110, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 110, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 110, reps: 41,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 120, reps: 6,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 120, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 120, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 120, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 130, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 130, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 130, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 130, reps: 40,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 140, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 140, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 140, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 140, reps: 39,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 150, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 150, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 150, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 150, reps: 38,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips', operator: Operator.LESS_THAN },
  { weight: 160, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 160, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 160, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 160, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 170, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 170, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 170, reps: 27,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 170, reps: 37,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 180, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 180, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 180, reps: 26,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 180, reps: 36,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 190, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 190, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 190, reps: 25,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 190, reps: 35,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 200, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 200, reps: 16,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 200, reps: 24,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 200, reps: 34,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 210, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 210, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 210, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 210, reps: 24,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 210, reps: 33,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 220, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 220, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 220, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 220, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 220, reps: 32,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 230, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 230, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 230, reps: 15,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 230, reps: 23,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 230, reps: 32,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 240, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 240, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 240, reps: 14,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 240, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 240, reps: 31,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 250, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 250, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 250, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 250, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 250, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 260, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 260, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 260, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 260, reps: 22,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 260, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 270, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 270, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 270, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 270, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 270, reps: 29,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 280, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 280, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 280, reps: 13,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 280, reps: 21,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 280, reps: 28,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 290, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 290, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 290, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 290, reps: 20,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 290, reps: 27,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 300, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 300, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 300, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 300, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 300, reps: 27,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },

  { weight: 310, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 310, reps: 7,   level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 310, reps: 12,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 310, reps: 19,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'dips' },
  { weight: 310, reps: 26,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'dips' },
]
