import { Level, Operator, Gender } from '@prisma/client'

export const chinUpsFemale80To89 = [
  { weight: 90, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 90, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 90, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 90, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 90, reps: 9,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 100, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 100, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 100, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 100, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 100, reps: 8,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 110, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 110, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 110, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 110, reps: 8,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 120, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 120, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 120, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 120, reps: 8,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 130, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 130, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 130, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 130, reps: 8,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 140, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 140, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 140, reps: 5,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 140, reps: 7,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 150, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 150, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 150, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 150, reps: 7,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 160, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 160, reps: 3,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 160, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 160, reps: 7,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 170, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 170, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 170, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 170, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 170, reps: 7,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 180, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 180, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 180, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 180, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 180, reps: 6,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 190, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 190, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 190, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 190, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 190, reps: 6,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 200, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 200, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 200, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 200, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 200, reps: 6,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 210, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 210, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 210, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 210, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 210, reps: 5,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 220, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 220, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 220, reps: 2,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 220, reps: 4,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 220, reps: 5,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 230, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 230, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 230, reps: 1,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 230, reps: 3,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 230, reps: 5,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 240, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 240, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 240, reps: 1,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 240, reps: 3,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 240, reps: 4,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 250, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 250, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 250, reps: 1,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 250, reps: 3,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 250, reps: 4,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: 260, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 260, reps: 1,  level: Level.INTERMEDIATE, age: 0, gender: Gender.FEMALE, exercise: 'chinUps', operator: Operator.LESS_THAN },
  { weight: 260, reps: 1,  level: Level.PROFICIENT,   age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 260, reps: 3,  level: Level.ADVANCED,     age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: 260, reps: 4,  level: Level.ELITE,        age: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
]
