import { Level, Gender, AgeRange, WeightRange, ExerciseName } from '@prisma/client'

export const chinUpsFemale70To79 = [
  { weight: WeightRange.NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.NINETY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.NINETY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.NINETY, reps: 7,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.NINETY, reps: 11,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED, reps: 7,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED, reps: 10,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 7,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TEN, reps: 10,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 7,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_TWENTY, reps: 10,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 6,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_THIRTY, reps: 10,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 6,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FORTY, reps: 9,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 6,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_FIFTY, reps: 9,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 6,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SIXTY, reps: 8,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 6,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_SEVENTY, reps: 8,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 5,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_EIGHTY, reps: 8,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 3,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 5,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.ONE_HUNDRED_NINETY, reps: 7,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED, reps: 5,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED, reps: 7,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 4,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TEN, reps: 7,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 4,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_TWENTY, reps: 7,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 4,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_THIRTY, reps: 6,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 4,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FORTY, reps: 6,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 2,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 4,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_FIFTY, reps: 6,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },

  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,   level: Level.NOVICE,       ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,  level: Level.INTERMEDIATE, ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 1,  level: Level.PROFICIENT,   ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 3,  level: Level.ADVANCED,     ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
  { weight: WeightRange.TWO_HUNDRED_SIXTY, reps: 6,  level: Level.ELITE,        ageRange: 0, gender: Gender.FEMALE, exercise: 'chinUps' },
]
