import { Level, Operator, Gender } from '@prisma/client'

export const standardsMale24To39 = [
  { weight: 110, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 110, reps: 14,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 41,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 74,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 110, reps: 111,  level: Level.ELITE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 120, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 120, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 41,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 73,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 120, reps: 108,  level: Level.ELITE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 130, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 130, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 41,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 71,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 130, reps: 105,  level: Level.ELITE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 140, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 140, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 41,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 70,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 140, reps: 102,  level: Level.ELITE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 150, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp', operator: Operator.LESS_THAN },
  { weight: 150, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 41,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 68,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 150, reps: 99,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 160, reps: 1,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 40,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 67,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 160, reps: 97,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 170, reps: 2,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 40,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 66,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 170, reps: 94,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 180, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 39,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 64,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 180, reps: 92,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 190, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 39,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 63,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 190, reps: 89,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 200, reps: 3,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 38,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 61,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 200, reps: 87,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 210, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 37,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 60,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 210, reps: 85,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 220, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 37,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 59,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 220, reps: 83,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 230, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 18,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 36,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 57,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 230, reps: 81,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 240, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 34,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 56,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 240, reps: 79,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 250, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 35,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 55,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 250, reps: 77,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 260, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 34,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 54,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 260, reps: 75,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 270, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 17,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 33,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 53,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 270, reps: 73,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 280, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 33,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 51,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 280, reps: 72,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 290, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 32,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 50,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 290, reps: 70,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 300, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 16,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 31,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 49,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 300, reps: 69,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },

  { weight: 310, reps: 4,   level: Level.NOVICE,       age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 15,  level: Level.INTERMEDIATE, age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 31,  level: Level.PROFICIENT,   age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 48,  level: Level.ADVANCED,     age: 0, gender: Gender.MALE, exercise: 'pushUp' },
  { weight: 310, reps: 67,  level: Level.ELITE,        age: 0, gender: Gender.MALE, exercise: 'pushUp' },
]
